#!/bin/bash
MACKEY_HOME=/data/picsl/mackey_group
project_dir=/jux/mackey_group/Ursula/projects/in_progress/within_between_network_conn_CBPD
sublist_dir=/data/jux/mackey_group/Ursula/projects/in_progress/within_between_network_conn_CBPD/data/subjectLists
#tools_dir=${MACKEY_HOME}/tools/singularity
tools_dir=/data/joy/BBL/applications/bids_apps #eventually check on that this hasn't changed.

FULL_COHORT=${sublist_dir}/n19_all_longitudinal_usable_t1_rest_1mm_outliers_10_2mm_nosleep_101119.csv

#FULL_COHORT=${sublist_dir}/n2_test.csv
NJOBS=`wc -l < $FULL_COHORT`

if [[ ${NJOBS} == 0 ]]; then
    echo 'you dont have enough lines in your csv file'
    exit 0
fi
#NJOBS=2

cat << EOF > xcpParallel.sh
#$ -j y
#$ -q all.q,basic.q,himem.q,gpu.q
#$ -l h_vmem=19.1G,s_vmem=19.0G
#$ -o /data${project_dir}/output/qsub_output
#$ -t 1-${NJOBS}

# Adjust these so they work on your system
SNGL=/share/apps/singularity/2.5.1/bin/singularity
SIMG=${tools_dir}/xcpEngine.simg
FULL_COHORT=${FULL_COHORT}

# Create a temp cohort file with 1 line
HEADER=\$(head -n 1 \$FULL_COHORT)
LINE_NUM=\$( expr \$SGE_TASK_ID + 1 )
LINE=\$(awk "NR==\$LINE_NUM" \$FULL_COHORT)
TEMP_COHORT=\${FULL_COHORT}.\${SGE_TASK_ID}.csv
echo \$HEADER > \$TEMP_COHORT
echo \$LINE >> \$TEMP_COHORT

\$SNGL run --cleanenv -B /data:/mnt \$SIMG \\
  -c /mnt\${TEMP_COHORT#/data} \\
  -d /mnt${project_dir}/code/ppc/fc-36p-nogsr-meancsfwm-spkreg-dropvols.dsn \\
  -o /mnt/picsl/mackey_group//BPD/CBPD_bids/derivatives/xcpEngine_nogsr_spkreg_fd1.25dvars2_drpvls \\
  -i \$TMPDIR

EOF

qsub xcpParallel.sh
