#!/bin/sh

#Loop script for FMRIPREP
#$ -j y
#$ -t 1-7
#$ -l h_vmem=20.1G,s_vmem=20G
#$ -q all.q,basic.q,himem.q,gpu.q
#$ -o /data/picsl/mackey_group/Ursula/projects/in_progress/within_between_network_conn_CBPD/output/qsub_output
unset PYTHONPATH;
URSULA_PROJ=/data/picsl/mackey_group/Ursula/projects/in_progress
ERROR_DIR=/data/picsl/mackey_group/Ursula/projects/in_progress/within_between_network_conn_CBPD/output/qsub_output
SUBLIST_DIR=${URSULA_PROJ}/within_between_network_conn_CBPD/data/subjectLists
SUB_FILE=${SUBLIST_DIR}/n7_add_subjs_usable_t1_rest_1mm_outliers_10_2mm_31019
SCRIPTS_DIR=${URSULA_PROJ}/within_between_network_conn_CBPD/code/ppc

mapfile -t ARRAY < ${SUB_FILE}

LENGTH=${#ARRAY[@]}

i=`expr ${SGE_TASK_ID} - 1`

if [[ $i -ge ${LENGTH} ]]; then
 echo 'Array index > than number of elements'

else
 SUB=${ARRAY[$i]}

bash ${SCRIPTS_DIR}/mriqc_cmd.sh ${SUB}

fi
